version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Webapi/Dockerfile
    volumes:
     - ./Webapi/App_Data:/home
     - ./Webapi/Storage:/home
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - ./Database/employee.sql:/docker-entrypoint-initdb.d/employee.sql
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
