CREATE DATABASE employee_sample;

\c employee_sample;

/* CREATE TABLE "employee" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    photo VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); */

CREATE TABLE IF NOT EXISTS public.employee
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    age integer NOT NULL,
    registration integer NOT NULL,
    "position" text COLLATE pg_catalog."default" NOT NULL,
    salary real NOT NULL,
    photo text COLLATE pg_catalog."default",
    CONSTRAINT "PK_employee" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attendance
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "employeeId" integer NOT NULL,
    date timestamp with time zone NOT NULL,
    "entryTime" timestamp with time zone NOT NULL,
    "exitTime" timestamp with time zone,
    CONSTRAINT "PK_attendance" PRIMARY KEY (id)
);

INSERT INTO public.employee (id, name, age, registration, position, salary, photo)
VALUES  (9, 'Manoel Malon Costa de Moura', 23, 252411, 'Engenheiro', 2400, 'Storage\00038-50-removebg-preview.png'),
        (42, 'Amanda de Castro Souza', 26, 15154, 'Estagiária', 3200, 'Storage\00010-45-removebg-preview.png');
